/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Grid: typeof import('./components/Grid/index.vue')['default']
    GridItem: typeof import('./components/Grid/components/GridItem.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    Pagination: typeof import('./components/SimpleTable/components/Pagination.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFormDatePicker: typeof import('./components/SearchForm/modules/SchemaFormDatePicker.vue')['default']
    SchemaFormInput: typeof import('./components/SearchForm/modules/SchemaFormInput.vue')['default']
    SchemaFormSelect: typeof import('./components/SearchForm/modules/SchemaFormSelect.vue')['default']
    SearchForm: typeof import('./components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./components/SearchForm/components/SearchFormItem.vue')['default']
    SimpleTable: typeof import('./components/SimpleTable/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./components/SimpleTable/components/TableColumn.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
